services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase 
    ports:
      - "8080:8080" 
    volumes:
      - ./data:/pb/pb_data 
    environment:
      PB_VERSION: 0.23.3 
      SUPERUSER_EMAIL: "admin@example.com"
      SUPERUSER_PASSWORD: "password"
