services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase 
    ports:
      - "8080:8080" 
    volumes:
      - ./data:/pb/pb_data 
    environment:
      PB_VERSION: "${PB_VERSION}"
      SUPERUSER_EMAIL: "${POCKETBASE_ADMIN_EMAIL}"
      SUPERUSER_PASSWORD: "${POCKETBASE_ADMIN_PASSWORD}"
